CC = gcc

all: Question1 Question2 Question3 Question4 Question5

Question1: question1.c
	$(CC) -o Question1 question1.c

Question2: question2.c
	$(CC) -o Question2 question2.c

Question3: question3.c
	$(CC) -o Question3 question3.c

Question4: question4.c
	$(CC) -o Question4 question4.c

Question5: question5.c
	$(CC) -o Question5 question5.c

clean:
	rm -f Question1 Question2 Question3 Question4 Question5 *.o
